service: vanity

frameworkVersion: "2"

provider:
  profile: serverless-admin
  region: us-west-2
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.vanity
#
